name: 'TestAction'
description: 'A test action to understand lifecycle of actions'
author: 'anuraag016'
inputs:
  myInput:
    description: 'input description here'
    default: 'default value if applicable'
  milliseconds:
    description: 'milliseconds to wait'
    default: 500
runs:
  using: 'node12'
  main: 'dist/index.js'
