name: "Testing"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
  workflow_dispatch:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Hello world
      id: hello
      uses: anuraag016/TestAction@v1.0
      with: 
        milliseconds: 1000
    - name: Get the output time
      run: |
            echo "The time was ${{ steps.hello.outputs.time }}"
            echo $GITHUB_EVENT_NAME
            export GITHUB_EVENT_NAME=test
            echo $GITHUB_EVENT_NAME
            echo 
            cat $GITHUB_EVENT_PATH
            echo test > $GITHUB_EVENT_PATH
            echo 
            cat $GITHUB_EVENT_PATH
    - name: Get the output EVENT
      run: |
            set
            echo "The time was ${{ steps.hello.outputs.time }}"
            echo $GITHUB_EVENT_NAME
            export GITHUB_EVENT_NAME=test
            echo $GITHUB_EVENT_NAME
            echo 
            cat $GITHUB_EVENT_PATH
            set
